# Cargo-deny configuration for cargo-warden

[bans]
multiple-versions = "warn"
wildcards = "allow"

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-3.0", "Zlib"]
confidence-threshold = 0.8

[advisories]
ignore = ["RUSTSEC-2024-0370"] # proc-macro-error is unmaintained but required by aya

[sources]
unknown-registry = "warn"
unknown-git = "warn"
