# Cargo-deny configuration for cargo-warden

[bans]
multiple-versions = "warn"
wildcards = "allow"

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-3.0", "Zlib"]
confidence-threshold = 0.8

[sources]
unknown-registry = "warn"
unknown-git = "warn"
