[package]
name = "agent-lite"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
aya = { version = "0.13" }
bpf-api = { path = "../bpf-api" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

anyhow = "1"
log = "0.4"
systemd-journal-logger = "2.2"
libc = "0.2"

tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"], optional = true }
tonic = { version = "0.10", features = ["transport"], optional = true }
prost = { version = "0.12", optional = true }
tokio-stream = { version = "0.1", features = ["sync"], optional = true }
futures-core = { version = "0.3", optional = true }
futures-util = { version = "0.3", optional = true }

[build-dependencies]
tonic-build = { version = "0.10", optional = true }

[features]
default = []
grpc = ["tonic", "prost", "tokio", "tokio-stream", "tonic-build", "futures-core", "futures-util"]

[package.metadata.cargo-machete]
ignored = ["prost"]

[dev-dependencies]
tempfile = "3"
