[package]
name = "qqrm-cargo-warden"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Command-line interface for the cargo-warden sandbox."
repository = "https://github.com/qqrm/cargo-warden"
homepage = "https://github.com/qqrm/cargo-warden"
documentation = "https://docs.rs/qqrm-cargo-warden"
readme = "../../README.md"

[dependencies]
anyhow = "1"
aya = "0.13"
clap = { version = "4", features = ["derive"] }
libseccomp = "0.3"
libc = "0.2"
policy-core = { package = "qqrm-policy-core", version = "0.1.0", path = "../policy-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

[dev-dependencies]
serial_test = "3"
qqrm-agent-lite = { path = "../agent-lite" }
assert_cmd = "2"
tempfile = "3"

[[bin]]
name = "cargo-warden"
path = "src/main.rs"
