[package]
name = "qqrm-proc-macro-hog"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
qqrm-proc-macro-hog-macro = { path = "proc-macro-hog-macro", version = "0.1.0" }
