name: 'Warden CI'
description: 'Run cargo-warden in CI and upload SARIF report.'
inputs:
  command:
    description: 'Cargo command to run under cargo-warden'
    required: false
    default: 'build'
  mode:
    description: 'Sandbox mode to use (observe or enforce)'
    required: false
    default: 'enforce'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y pkg-config libseccomp-dev
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install cargo-warden
      shell: bash
      run: cargo install --path crates/cli
    - name: Run cargo warden ${{ inputs.command }}
      shell: bash
      env:
        QQRM_WARDEN_FAKE_SANDBOX: "1"
      run: |
        set -euo pipefail
        MODE="${{ inputs.mode }}"
        case "$MODE" in
          observe|enforce) ;;
          *)
            echo "Invalid mode: $MODE" >&2
            exit 1
            ;;
        esac
        set +e
        cargo warden --mode "$MODE" ${{ inputs.command }}
        status=$?
        set -e
        if [[ $status -ne 0 ]]; then
          if [[ "$MODE" == "enforce" ]]; then
            echo "::warning::cargo warden reported violations in enforce mode (exit $status)" >&2
          else
            exit $status
          fi
        fi
    - name: Generate SARIF report
      shell: bash
      env:
        QQRM_WARDEN_FAKE_SANDBOX: "1"
      run: cargo warden report --output warden.sarif
    - name: Upload SARIF report
      if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: warden.sarif
      continue-on-error: true
