dev_comments = false
skip_readme = false

[hunspell]
lang = "en_US"
search_dirs = ["."]
skip_os_lookups = false
use_builtin = true
extra_dictionaries = ["tech.dic"]

[hunspell.quirks]
allow_concatenation = true
allow_dashes = true
allow_emojis = true
check_footnote_references = true
