name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - run: cargo fmt --all -- --check
      - run: cargo check --tests --benches
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test
      - run: rm -rf "$CARGO_HOME/advisory-dbs/advisory-db-3157b0e258782691" && git clone --depth 1 https://github.com/RustSec/advisory-db "$CARGO_HOME/advisory-dbs/advisory-db-3157b0e258782691"
      - run: cargo deny check --disable-fetch
      - run: cargo machete
        continue-on-error: true
