name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - run: cargo fmt --all -- --check
      - run: cargo check --tests --benches
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test
      - run: cargo deny check
      - run: cargo machete
        continue-on-error: true
