name: Publish Crates

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure git remote
        run: ./repo_setup.sh
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces --locked
      - name: Publish crates in dependency order
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          set -euo pipefail
          cargo workspaces publish \
            --publish-as-is \
            --skip-published \
            --no-git-commit \
            --publish-interval 45 \
            -y
