name: Publish Crates

on:
  push:
    tags: ['v*']
  workflow_dispatch:

concurrency:
  group: publish-crates-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure git remote
        run: ./repo_setup.sh
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish crates in dependency order
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: ./scripts/publish-crates.sh
