name: Publish

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: CI
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          set -e
          crates="bpf-api bpf-core policy-core policy-compiler agent-lite testkits cargo-warden"
          for crate in $crates; do
            cargo publish -p "$crate" --token "${{ secrets.CRATES_IO_TOKEN }}"
          done
