name: Publish

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          set -e
          crate_dirs="crates/bpf-api crates/bpf-core crates/policy-core crates/policy-compiler crates/agent-lite crates/testkits crates/cli"
          for dir in $crate_dirs; do
            name=$(sed -n 's/^name = "\(.*\)"/\1/p' "$dir/Cargo.toml")
            cargo publish -p "$name" --token "${{ secrets.CRATES_IO_TOKEN }}"
          done
